In [16]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [8]:
url = "https://www.espncricinfo.com/records/tournament/team-match-results/indian-premier-league-2023-15129"

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"}

page = requests.get(url=url, headers=headers)
soup = BeautifulSoup(page.content, "html.parser")

In [14]:
matches_list = []
matches = soup.select("table > tbody > tr")

for match in matches:
    m = {
        "team_1": match.select_one("td:nth-child(1)").text,
        "team_2": match.select_one("td:nth-child(2)").text,
        "winner": match.select_one("td:nth-child(3)").text,
        "margin": match.select_one("td:nth-child(4)").text
    }
    matches_list.append(m)

In [19]:
df = pd.DataFrame(matches_list)
df

          team_1       team_2        winner     margin
0         Titans  Super Kings        Titans  5 wickets
1   Punjab Kings          KKR  Punjab Kings     7 runs
2   Super Giants     Capitals  Super Giants    50 runs
3      Sunrisers       Royals        Royals    72 runs
4            RCB       Mumbai           RCB  8 wickets
..           ...          ...           ...        ...
69           RCB       Titans        Titans  6 wickets
70   Super Kings       Titans   Super Kings    15 runs
71  Super Giants       Mumbai        Mumbai    81 runs
72        Titans       Mumbai        Titans    62 runs
73        Titans  Super Kings   Super Kings  5 wickets

[74 rows x 4 columns]

In [25]:
names = {
    "Titans": "GT",
    "Punjab Kings": "PBKS",
    "Super Giants": "LSG",
    "Sunrisers": "SRH",
    "Royals": "RR",
    "Capitals": "DC",
    "Mumbai": "MI",
    "Super Kings": "CSK"
    
}

df["team_1"] = df["team_1"].map(names)

# df["team_1"] = df["team_1"].replace(
#     ["Titans", "Punjab Kings", "Super Giants", "Sunrisers", "Royals", "Capitals", "Mumbai", "Super Kings"],
#     ["GT", "PBKS", "LSG", "SRH", "RR", "DC", "MI", "CSK"]
# )
print(df.to_string())

   team_1        team_2        winner     margin
0     NaN   Super Kings        Titans  5 wickets
1     NaN           KKR  Punjab Kings     7 runs
2     NaN      Capitals  Super Giants    50 runs
3     NaN        Royals        Royals    72 runs
4     NaN        Mumbai           RCB  8 wickets
5     NaN  Super Giants   Super Kings    12 runs
6     NaN        Titans        Titans  6 wickets
7     NaN  Punjab Kings  Punjab Kings     5 runs
8     NaN           RCB           KKR    81 runs
9     NaN     Sunrisers  Super Giants  5 wickets
10    NaN      Capitals        Royals    57 runs
11    NaN   Super Kings   Super Kings  7 wickets
12    NaN           KKR           KKR  3 wickets
13    NaN  Punjab Kings     Sunrisers  8 wickets
14    NaN  Super Giants  Super Giants   1 wicket
15    NaN        Mumbai        Mumbai  6 wickets
16    NaN        Royals        Royals     3 runs
17    NaN        Titans        Titans  6 wickets
18    NaN     Sunrisers     Sunrisers    23 runs
19    NaN      Capitals           RCB    23 runs
20    NaN  Punjab Kings  Punjab Kings  2 wickets
21    NaN           KKR        Mumbai  5 wickets
22    NaN        Royals        Royals  3 wickets
23    NaN   Super Kings   Super Kings     8 runs
24    NaN        Mumbai        Mumbai    14 runs
25    NaN  Super Giants  Super Giants    10 runs
26    NaN           RCB           RCB    24 runs
27    NaN           KKR      Capitals  4 wickets
28    NaN     Sunrisers   Super Kings  7 wickets
29    NaN        Titans        Titans     7 runs
30    NaN  Punjab Kings  Punjab Kings    13 runs
31    NaN        Royals           RCB     7 runs
32    NaN   Super Kings   Super Kings    49 runs
33    NaN      Capitals      Capitals     7 runs
34    NaN        Mumbai        Titans    55 runs
35    NaN           KKR           KKR    21 runs
36    NaN   Super Kings        Royals    32 runs
37    NaN  Super Giants  Super Giants    56 runs
38    NaN        Titans        Titans  7 wickets
39    NaN     Sunrisers     Sunrisers     9 runs
40    NaN  Punjab Kings  Punjab Kings  4 wickets
41    NaN        Royals        Mumbai  6 wickets
42    NaN           RCB           RCB    18 runs
43    NaN      Capitals      Capitals     5 runs
44    NaN   Super Kings     no result          -
45    NaN        Mumbai        Mumbai  6 wickets
46    NaN           KKR           KKR     5 runs
47    NaN        Titans        Titans  9 wickets
48    NaN        Mumbai   Super Kings  6 wickets
49    NaN           RCB      Capitals  7 wickets
50    NaN  Super Giants        Titans    56 runs
51    NaN     Sunrisers     Sunrisers  4 wickets
52    NaN  Punjab Kings           KKR  5 wickets
53    NaN           RCB        Mumbai  6 wickets
54    NaN      Capitals   Super Kings    27 runs
55    NaN        Royals        Royals  9 wickets
56    NaN        Titans        Mumbai    27 runs
57    NaN  Super Giants  Super Giants  7 wickets
58    NaN  Punjab Kings  Punjab Kings    31 runs
59    NaN           RCB           RCB   112 runs
60    NaN           KKR           KKR  6 wickets
61    NaN     Sunrisers        Titans    34 runs
62    NaN        Mumbai  Super Giants     5 runs
63    NaN      Capitals      Capitals    15 runs
64    NaN           RCB           RCB  8 wickets
65    NaN        Royals        Royals  4 wickets
66    NaN   Super Kings   Super Kings    77 runs
67    NaN  Super Giants  Super Giants      1 run
68    NaN     Sunrisers        Mumbai  8 wickets
69    NaN        Titans        Titans  6 wickets
70    NaN        Titans   Super Kings    15 runs
71    NaN        Mumbai        Mumbai    81 runs
72    NaN        Mumbai        Titans    62 runs
73    NaN   Super Kings   Super Kings  5 wickets